Repository wecode-bootcamp-korea/22-1st-DrMozzarella-frontend, pull requests merged in 2021-07, with the labels that each got.

#2 [22기 이종민] Add: Sign Up 페이지 1차 피드백 반영 수정버전
  package-lock.json
  package.json
  src/Validation/Validation.js
  src/index.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청, Status: 수정 요청

#1 [22기 황소미] Add: shop페이지 레이아웃 구현
  package-lock.json
  public/images/Shop/arrow.jpeg
  public/images/Shop/header1.jpeg
  src/components/CategoryHeader/Header.js
  src/components/CategoryHeader/Header.scss
  src/pages/Detail/Detail.js
  src/pages/Shop/Header/Header.js
  src/pages/Shop/Header/Header.scss
  src/pages/Shop/ProductList/ProductList.js
  src/pages/Shop/ProductList/ProductList.scss
  src/pages/Shop/Shop.js
  src/pages/Shop/Shop.scss
  src/pages/Shop/SideMenuList/SideMenu/SideMenu.js
  src/pages/Shop/SideMenuList/SideMenu/SideMenu.scss
  src/pages/Shop/SideMenuList/SideMenuList.js
  src/pages/Shop/SideMenuList/SideMenuList.scss
  src/pages/Shop/Sort/Sort.js
  src/pages/Shop/Sort/Sort.scss
Labels: Status: 리뷰 요청

#7 [22기 황소미] Add: Category Header Component (URGENT!!!!!)
  src/components/categoryHeader/CategoryHeader.js
  src/components/categoryHeader/CategoryHeader.scss
Labels: Status: Accepted

#5 [22기 이종민] Add: Sign Up 피드백 2차 반영 (Urgent)
  src/config.js
  src/index.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 수정 요청

#8 [22기 이종민] Login 1차 피드백 반영 및 Nav 바 & Font 반영
  src/Routes.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/config.js
  src/index.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#9 [22기 황소미] Add: 카드 컴포넌트 레이아웃 리팩토링, props 추가
  src/components/Card/Card.js
  src/components/Card/Card.scss
Labels: Status: 리뷰 요청

#12 Update README.md_
  README.md
Labels: Status: 리뷰 요청

#14 [22기 박정훈] Add: footer pr 피드백 사항 수정 완료
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#15 [22기 박정훈] Add: 카드 컴포넌트 버튼 크기 수정
  src/components/Card/Card.scss
Labels: Status: 리뷰 요청

#4 [22기 박정훈] Add: 메인페이지 레이아웃 및 슬라이더 2차 리뷰 반영 완료
  package-lock.json
  public/data/CarouselData.json
  src/Routes.js
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.scss
  src/pages/Login/Login.scss
  src/pages/Main/CardLarge/CardLarge.js
  src/pages/Main/CardLarge/CardLarge.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/Slogan/Slogan.js
  src/pages/Main/Slogan/Slogan.scss
Labels: Status: 리뷰 요청

#6 [22기 황소미] Add: 리뷰 반영 및 validation 함수 추가
  public/data/detail.json
  public/data/productDetail.json
  public/data/productImages.json
  public/data/products.json
  public/images/product.jpeg
  public/images/product1.jpeg
  public/images/product2.jpeg
  public/images/product3.jpeg
  src/components/Card/Card.js
  src/components/Card/Card.scss
  src/components/CategoryImg/CategoryImg.js
  src/components/CategoryImg/CategoryImg.scss
  src/components/Footer/Footer.scss
  src/pages/Detail/CompareProduct/CompareProduct.js
  src/pages/Detail/CompareProduct/CompareProduct.scss
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Detail/ProductDetail/Gallery/Gallery.js
  src/pages/Detail/ProductDetail/Gallery/Gallery.scss
  src/pages/Detail/ProductDetail/ProductDetail.js
  src/pages/Detail/ProductDetail/ProductDetail.scss
  src/pages/Detail/ProductFunc/ProductFunc.js
  src/pages/Detail/ProductFunc/ProductFunc.scss
  src/pages/Detail/PromotionImg/PromotionImg.js
  src/pages/Detail/PromotionImg/PromotionImg.scss
  src/pages/Detail/Routine/Routine.js
  src/pages/Detail/Routine/Routine.scss
  src/utils.js
Labels: Status: 리뷰 요청

#16 [22기 이종민] Cart 2차 피드백 반영 수정 및 카트가 비었을 때 레이아웃 변경
  src/Fomating.js
  src/components/Footer/Footer.scss
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartlList/CartList.js
  src/pages/Cart/CartlList/CartList.scss
  src/pages/Login/Login.js
  src/pages/SignUp/SignUp.js
Labels: Status: 리뷰 요청

#21 [22기 박정훈] Add: 공용컴포넌트 Card, CtegoryImg 수정 (URGENT)
  src/components/Card/Card.js
  src/components/Card/Card.scss
  src/components/CategoryImg/CategoryImg.js
  src/components/CategoryImg/CategoryImg.scss
Labels: Status: 수정 요청

#22 [22기 박정훈] 카트 Add: 함수 컴포넌트화 이외에 반영 완료 (URGENT)
  src/components/Card/Card.js
  src/components/Card/Card.scss
  src/components/CategoryImg/CategoryImg.js
Labels: Status: 리뷰 요청

#17 [22기 박정훈] Add: Nav바 dropdown 구현
  public/data/nav.json
  src/Routes.js
  src/components/CategoryImg/CategoryImg.js
  src/components/Nav/DropDownNav.js
  src/components/Nav/DropDownNav.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Detail/Detail.js
  src/pages/Detail/ProductDetail/Gallery/Gallery.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#20 [22기 박정훈] Add: 카드 컴포넌트를 활용한 케러셀 구현 및 목데이터 연결 완료 (URGENT)
  public/data/bestSeller.json
  src/components/Card/Card.js
  src/components/Card/Card.scss
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: Accepted

#18 [22기 황소미] Add: detail 페이지 기능 수정
  public/data/category.json
  public/data/detail.json
  public/data/shop.json
  src/Routes.js
  src/components/Card/Card.scss
  src/config.js
  src/pages/Detail/CompareProduct/CompareProduct.js
  src/pages/Detail/CompareProduct/CompareProduct.scss
  src/pages/Detail/Detail.js
  src/pages/Detail/ProductDetail/Gallery/Gallery.js
  src/pages/Detail/ProductDetail/ProductDetail.js
  src/pages/Detail/ProductDetail/ProductDetail.scss
  src/pages/Detail/Routine/Routine.js
  src/pages/Shop/ProductList/ProductList.js
  src/pages/Shop/Shop.js
  src/pages/Shop/Shop.scss
  src/pages/Shop/SideMenuList/SideMenu/SideMenu.js
  src/pages/Shop/SideMenuList/SideMenuList.js
  src/pages/Shop/Sort/Sort.js
Labels: Status: 리뷰 요청

#23 [22기 박정훈] 라우트 Nav 오류 해결 및 Nav 동적 라우팅 연결
  src/Routes.js
  src/components/Carousel/Carousel.js
  src/components/Nav/DropDownNav.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/CardLarge/CardLarge.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/Slogan/Slogan.scss
Labels: Status: 리뷰 요청

#19 [22기 이종민] Order & Cart 함수 부분 피드백 반영 (Address 페어 코딩 부분 제외)
  package-lock.json
  package.json
  src/Fomating.js
  src/Routes.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/CartlList/CartList.js
  src/pages/Order/Address/Address.js
  src/pages/Order/Order.js
  src/pages/Order/Order.scss
  src/pages/Order/Orderlist/Orderlist.js
  src/pages/Order/Orderlist/Orderlist.scss
  src/pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청

#24 [22기 황소미] 장바구니 추가기능 구현 완성!!!!
  src/components/Card/Card.js
  src/components/Card/Card.scss
  src/pages/Detail/Detail.js
  src/pages/Detail/ProductDetail/ProductDetail.js
  src/pages/Shop/Shop.js
Labels: Status: 리뷰 요청

#27 [22기 박정훈] 메인페이지 링크 수정
  package-lock.json
  src/components/Nav/DropDownNav.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Main/CardLarge/CardLarge.js
  src/pages/Main/CardLarge/CardLarge.scss
Labels: Status: 리뷰 요청

#28 [22기 이종민] [Modify] a Tag -> Link 로 변경 및 일부 margin 값 수정
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청

#31 로그인 로그아웃 버튼
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: Status: 리뷰 요청
